version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Copy Local
          path: ./TuyaSmartHomeSdkDemo
          command: cp local.properties.ci local.properties
      - run:
          name: Build app
          path: ./TuyaSmartHomeSdkDemo
          command: ./gradlew assembleDebug
